### ISSUE TITLE
[Error] Physical Repositories list

### ISSUE THREAD

**Issue by Devpap7** [jbox-web/redmine_git_hosting#528]
I've set up Redmine (2.6.2) with the git hosting plugin. Gitolite was allready working as well.
The Config Test tab ist all green, but there is also my first problem. The count of physical repositories in Gitolite is zero. The Gitolite banner is showing my indipendent created repositories. (What exactly is a physical repo?)
The log shows: `2015-10-28 20:12:41 +0100 [ERROR] Error while getting Gitolite physical repositories list`
       
    hello redmine, this is gitolite@october running gitolite3 v3.6.3-11-g2417156 on git 1.7.10.4

      R W	gitolite-admin
      R W	scripts
      R W	test     

These repos are accessible from my computer equipped with the ssh key pair. The newly, from redmine created repo, is not listed but also accessible. 

    $ ssh -i devpap_redmine gitolite@octoberinfo
    hello redmine_devpap7_5, this is gitolite@october running gitolite3 v3.6.3-11-g2417156 on git     1.7.10.4
    
     R W    brr2
     R W    project_test2
     R W    test

Theses repos aren't listed in redmine.
I've deleted all other problems from this post. There were just configuration problems.

**Comment by Devpap7** [comment]
update:
Cloning is working good. I've changed the hooks_url to https://october/redmine
Changes are displayed in my repository tab of the project.
There still erros while pushing to remote repo:

    $ git push -u origin master
    Counting objects: 3, done.
    Delta compression using up to 3 threads.
    Compressing objects: 100% (2/2), done.
     Writing objects: 100% (3/3), 345 bytes | 0 bytes/s, done.
     Total 3 (delta 0), reused 0 (delta 0)
     remote:
     remote: Notifying Redmine about changes to this repository : 'test/brr2' ...
     remote: HTTP_ERROR : Connection refused - connect(2)
     remote:
     remote: Looking for additional global post-receive hooks...
     remote:   - Global hooks found : ["hooks/post-receive.d/mail_notifications"]
     remote:
     remote: Looking for additional local post-receive hooks...
     remote:   - No local hooks found
     remote:
     remote: Calling additional post-receive hooks...
     remote:   - Executing extra hook 'hooks/post-receive.d/mail_notifications'
     remote:     multimailhook is disabled
     remote:
     To gitbox:brr2
      * [new branch]      master -> master
     Branch master set up to track remote branch master from origin.

Where is my mistake?

**Comment by n-rodriguez** [comment]
> What exactly is a physical repo?

A physical repo is a repository in Gitolite : hence a repository declared in Gitolite configuration file.
It must be distinguished from Redmine repositories : a repository declared in Redmine database.
(A Gitolite repo may not exist in Redmine. The contrary is also true).

This list is provided by the Gitolite command : ```gitolite list-phy-repos```.

**Comment by Devpap7** [comment]
Thank you for this explanation. My example at the top of this page shows a valid combination for redmine and gitolite repos. The repo test is listed in both infos because of the @all flag. Is this the reason I get the error message in the log files?

**Comment by n-rodriguez** [comment]
> Why is my physical repo count zero?

Can please you run this command as ```redmine``` user :
```sudo -n -u git -i gitolite list-phy-repos```

**Comment by Devpap7** [comment]
redmine@Charon:/home/pi$ sudo -n -u git -i gitolite list-phy-repos
sudo: sorry, a password is required to run sudo

I haven´t set a password for the user redmine. Even without the -n flag the command is not working.

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-6-configure-sudo

**Comment by Devpap7** [comment]
Thank you, I think I got a configuration problem. I'll have to check this first. My git user doesn't have home directory.

**Comment by n-rodriguez** [comment]
> My git user doesn't have home directory.

This is bad :)

**Comment by Devpap7** [comment]
I've checked your "Get started" guide. I think in step 5 I switched to the gitolite user and changed the .gitolute.rc file in the home directory of this user. can I stil get the pyhsical repo list or do I have reinstall and reconfigure the plugin or even git and gitolite.

**Comment by n-rodriguez** [comment]
> an I stil get the pyhsical repo list or do I have reinstall and reconfigure the plugin or even git and gitolite.

Nope. It should work now.

**Comment by Devpap7** [comment]
Sadly it is not working. I'll have to get to it tomorrow. Still an error in my log file and count at zero for the physical repos.
`2015-11-26 22:38:47 +0100 [ERROR] Error while getting Gitolite physical repositories list`

**Comment by n-rodriguez** [comment]
> I've changed my configuration variables to match this.

That's a good thing, but check that you can run this command as redmine user :
``` sudo -n -u git -i gitolite list-phy-repos```

**Comment by Devpap7** [comment]
Nope still nothing. Getting the error with the missing home directory. even if I'm using gitolite user. I found some differences in my configuration. maybe I'll retry the installation and configuration. This time I'll go with the user git. Just out of curiosity: Where can I find this gitolite command? This command isn't listed  gitoliteDir/bin/commands. Right now, I made a backup for this current system.  
Thank you for now. I will get back to you.

**Comment by n-rodriguez** [comment]
> Where can I find this gitolite command? This command isn't listed gitoliteDir/bin/commands. Right now, I made a backup for this current system.

It depends on how you installed Gitolite. It should be in ```<gitolite user home dir>/bin```

**Comment by Devpap7** [comment]
Okay. I tried to reinstall the plugin and ended up with another problem.
Up to (step 7)  everything went very vell. I get a positiv response to the command in step 7. But if I want to save the configuration in git_hosting_plugin I'll get an Internal Error. Sadky my gitolite version is unknown and mirror keys are not installed.

**Comment by Devpap7** [comment]
I may have found a solution. After reinstallation and downgrading to version v1.1.5 like said in bug report #544, everything is working well.
thank you for your support.
